name: Verification checks

on:
  pull_request:
    branches: [dev]
  push:
    branches: [dev]

jobs:
  quality_checks:
    name: Run quality checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Handle gradle execution permissions
        run: chmod +x gradlew

      - name: Build with gradle
        run: ./gradlew build

      - name: Run linting checks
        run: ./gradlew ktlintCheck
